<a href="https://colab.research.google.com/github/pius928/BIT4133-NLP-DeepLearning-Logbook/blob/main/Week_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.20.0


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

texts = [
    "I love natural language processing",
    "Natural language processing is interesting",
    "Deep learning improves NLP models",
    "Machine learning powers artificial intelligence",
    "Students enjoy learning NLP"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

print(tokenizer.word_index)

{'learning': 1, 'natural': 2, 'language': 3, 'processing': 4, 'nlp': 5, 'i': 6, 'love': 7, 'is': 8, 'interesting': 9, 'deep': 10, 'improves': 11, 'models': 12, 'machine': 13, 'powers': 14, 'artificial': 15, 'intelligence': 16, 'students': 17, 'enjoy': 18}


In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = tokenizer.texts_to_sequences(texts)

print("Sequences:")
print(sequences)

padded = pad_sequences(sequences)

print("\nPadded Sequences:")
print(padded)

Sequences:
[[6, 7, 2, 3, 4], [2, 3, 4, 8, 9], [10, 1, 11, 5, 12], [13, 1, 14, 15, 16], [17, 18, 1, 5]]

Padded Sequences:
[[ 6  7  2  3  4]
 [ 2  3  4  8  9]
 [10  1 11  5 12]
 [13  1 14 15 16]
 [ 0 17 18  1  5]]


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()

model.add(Embedding(input_dim=50, output_dim=8))

model.add(SimpleRNN(16))

model.add(Dense(10, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
import numpy as np

X_train = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

y_train = tf.keras.utils.to_categorical(
    [1,2,3,4],
    num_classes=10
)

history = model.fit(
    X_train,
    y_train,
    epochs=10,
    verbose=1
)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2500 - loss: 2.2958
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 2.2858
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 2.2757
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 2.2657
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 2.2556
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7500 - loss: 2.2454
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.7500 - loss: 2.2352
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7500 - loss: 2.2250
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7500 - loss: 2.2146
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 2.2041


In [6]:
prediction = model.predict(np.array([[1,2,3]]))

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step
[[0.10472326 0.1216792  0.10075002 0.0975611  0.09634845 0.09450597
  0.09014973 0.10237893 0.10317541 0.08872788]]


In [7]:
loss, accuracy = model.evaluate(
    X_train,
    y_train,
    verbose=0
)

print("Loss:", loss)
print("Accuracy:", accuracy)

Loss: 2.1934189796447754
Accuracy: 0.75
